[options]
admin_passwd = $pbkdf2-sha512$600000$0TpHyDnnfO8dYyzlPIfwfg$aJBTsTUAeVXZiJcyIPWeUXL/lUIbMx9BSCwq5haQqVkuPO.U8g8v6yuizu9OQkdtNxyq3UmD4fEO8mLQWRpSFA
db_host = localhost
db_port = 5432
db_user = odoo
db_password = 0625159120
addons_path = /data/odoo/metal-odoo18-p8179/addons,/data/odoo/metal-odoo18-p8179/myaddons,/data/odoo/metal-odoo18-p8179/communityaddons,/data/odoo/metal-odoo18-p8179/ocaaddons
xmlrpc_port = 9079
proxy_mode = True
log_level = error
logfile = /data/odoo/metal-odoo18-p8179/odoo-server.log
log_handler = [':INFO']
smtp_password = pNyirQPF'7x7$rw
smtp_port = 587
smtp_server = mail.infomaniak.com
smtp_ssl = True
smtp_user = franck@metallerie.xyz
dbfilter = ^metal-prod-18.*$
web.base.url = https://www.metallerie.xyz
wkhtmltopdf_path = /usr/local/bin/wkhtmltopdf

