# -*- coding: utf-8 -*-
{
    'name': 'Mindee Ocr api',
    'version': '18.0.1.0.0',
    'category': 'Accounting',
    'summary': """ mindee api """,
    'description': """ mindee api                    """,
    'author': 'hasabalrasool',
    'website': "https://sbs-cloud.com",
    'company': 'Source Bussiness Solutions',
    'depends': ['base', 'account','product'],
    'data': [
        'views/res_config_settings.xml',
        'views/account_move.xml',
        'views/product_assign_line_wizard.xml',
        'views/res_config_settings_views.xml',
        'security/ir.model.access.csv',
        'views/res_partner_view.xml',
        'views/labelstudio_history_views.xml',
        'data/ir_cron.xml',
        'data/ir_config_parameter.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
